# Generated by Django 2.2.6 on 2019-11-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='mol_weight',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalsetfacet',
            name='embedding',
            field=models.TextField(choices=[('3/RDK/MDS', '3/RDKit/Multidimensional Scaling'), ('3/RDK/NM-MDS', '3/RDKit/Non-Metric Multidimensional Scaling'), ('3/RDK/SMACOF', '3/RDKit/SMACOF Multidimensional Scaling'), ('3/RDK/NM-SMACOF', '3/RDKit/Non-Metric SMACOF Multidimensional Scaling')]),
        ),
        migrations.AlterField(
            model_name='computefacetjob',
            name='embedding',
            field=models.TextField(choices=[('3/RDK/MDS', '3/RDKit/Multidimensional Scaling'), ('3/RDK/NM-MDS', '3/RDKit/Non-Metric Multidimensional Scaling'), ('3/RDK/SMACOF', '3/RDKit/SMACOF Multidimensional Scaling'), ('3/RDK/NM-SMACOF', '3/RDKit/Non-Metric SMACOF Multidimensional Scaling')]),
        ),
    ]
