# Generated by Django 2.2.6 on 2019-10-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspace', '0002_auto_20191031_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicaltag',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
