# Generated by Django 2.2.6 on 2019-12-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspace', '0002_auto_20191126_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='tpsa',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
