# Generated by Django 2.2.6 on 2019-11-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cspace', '0003_auto_20191031_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalSetFascet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('sim_measure', models.TextField(choices=[('RDK/T', 'RDKit/Tanimoto')])),
                ('embedding', models.TextField(choices=[('3/RDK/MDS', '3/RDKit/Multidimensional Scaling')])),
                ('created', models.DateField(auto_now_add=True)),
                ('dist_json', models.TextField()),
                ('chem_ids_json', models.TextField()),
                ('chemical_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cspace.ChemicalSet')),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddedChemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cspace.Chemical')),
                ('fascet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cspace.ChemicalSetFascet')),
            ],
        ),
        migrations.CreateModel(
            name='ComputeFascetJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_measure', models.TextField(choices=[('RDK/T', 'RDKit/Tanimoto')])),
                ('embedding', models.TextField(choices=[('3/RDK/MDS', '3/RDKit/Multidimensional Scaling')])),
                ('status', models.IntegerField(choices=[(-1, 'Failed'), (0, 'Pending'), (1, 'Running'), (2, 'Done')])),
                ('chemical_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cspace.ChemicalSet')),
                ('fascet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cspace.ChemicalSetFascet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='chemicalsetfascet',
            constraint=models.UniqueConstraint(fields=('embedding', 'sim_measure', 'chemical_set'), name='fascet_identity'),
        ),
    ]
